# Generated by Django 4.0.4 on 2022-05-18 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='measurement',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
