# Generated by Django 4.0.4 on 2022-05-22 15:09

from django.db import migrations, models
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_inventoryitem_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='edit_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='location',
            field=mapbox_location_field.models.LocationField(map_attrs={'center': [-77.03, 38.91], 'zoom': 9}),
        ),
    ]
